### ISSUE TITLE
Subscribe to onVisibilityChange  event

### ISSUE THREAD

**Issue by YUcxovo** [linsyking/Messenger#12]
Subscribing the [onVisibilityChange](https://package.elm-lang.org/packages/elm/browser/latest/Browser-Events#onVisibilityChange) Msg is helpful when users switch to another window. Especially when dealing with the keydown Msg or a timer.

**Comment by YUcxovo** [comment]
Add `WindowVisibility` to `GlobalData` might be more convenient for users

**Comment by linsyking** [comment]
> Add `WindowVisibility` to `GlobalData` might be more convenient for users

Sounds reasonable.
