### ISSUE TITLE
[Enhancement] Volunteerily working on improving the documentation of messenger!

### ISSUE THREAD

**Issue by Monolitho** [linsyking/Messenger#19]
Hello, linsyking. I am a freshman who has just survived the VG100 using messenger. However, when I was using messenger, I think the cocumentation for each function is not very comprehensively written, and neither the manual nor the docs on the elm file itself provides the explanation, forcing me the read the raw code, which is not very easy for beginners. To address that, I hope I can help to improve the docs by adding more tips and usage in the docs. I have forked a copy of the repo. And I will start working from next week. I hope you can explain some of the functions to me when needed and provide suggestions and feedbacks on my docs. Thanks!
You can just go to my repo here: [repo](https://github.com/Monolitho/messenger-core) or contact me via mattermost (I am the one who asked for spritesheet of sound and collision box, and my surname is Zhang). Maybe we can have a meeting and figure out the roadmap.
Thank you again for creating messenger!

**Comment by linsyking** [comment]
That sounds great. We should have a meeting discussing the documentation. I will reply to you on mattermost.

**Comment by linsyking** [comment]
I think we could switch to HTML instead of typst to maintain the doc.

**Comment by Monolitho** [comment]
Could you tell me what is the timezone you are currently in? We can schedule a meeting based on that (I am not available now).

**Comment by linsyking** [comment]
We shall discuss this on mattermost.
