### ISSUE TITLE
SOM design

### ISSUE THREAD

**Issue by linsyking** [linsyking/Messenger#9]
Every ObjectMsg should derive from SOM message, i.e. they are able to do top-level calls directly.
Otherwise it is almost impossible for component writer to write a usable and general component.

```elm
type MsgBase a = SOMMsg SOM | OtherMsg a
```
Then,
```elm
type alias LayerMsg = MsgBase (LayerMsg_)
type alias ComponentMsg = MsgBase (ComponentMsg_)
```

And finally let messenger handle `SOMMsg`.
The side effect is that every component has the ability to call SOM APIs. (But you can still ban them in scene level)

**Comment by linsyking** [comment]
What's others opinions on this proposal?
@YUcxovo

**Comment by YUcxovo** [comment]
It is reasonable. But why make layers can also call SOM APIs, since we just try to solve the problems about writing general components?

**Comment by YUcxovo** [comment]
> It is reasonable. But why make layers can also call SOM APIs, since we just try to solve the problems about writing general components?

I see. so we still try to use the components -> layers -> scenes -> messenger chain to deal with the ComponentMsg, so that we have to change all the Msgs on this chain to SOMMsg?

**Comment by linsyking** [comment]
> > It is reasonable. But why make layers can also call SOM APIs, since we just try to solve the problems about writing general components?
> 
> I see. so we still try to use the components -> layers -> scenes -> messenger chain to deal with the ComponentMsg, so that we have to change all the Msgs on this chain to SOMMsg?

To MsgBase.

**Comment by YUcxovo** [comment]
GameComponentMsg seems to be lonely LOL
